---
- name: Download nvm installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh
    dest: /tmp/nvm-installer.sh
    mode: "0777"
  tags:
    - nvm_setup

- name: Execute the nvm-installer.sh
  ansible.builtin.command: /tmp/nvm-installer.sh
  become: true
  become_user: "{{ nvm_user }}"
  register: nvm_installer_has_been_executed
  changed_when: nvm_installer_has_been_executed.rc != 0
  tags:
    - nvm_setup

- name: Remove nvm-installer.sh
  ansible.builtin.file:
    path: /tmp/nvm-installer.sh
    state: absent
  tags:
    - nvm_setup
