#!/usr/bin/env ansible-playbook
---
-   hosts: webservers
    connection: local
    become: false
    roles:
        -   role: common
            become: true
            tags:
                - common

        -   role: php
            become: true
            vars:
                php_user: "{{ host_user }}"
                php_group: "{{ host_group }}"
            when: webservers_stack.php | default(true)
            tags:
                - php

        -   role: mysql
            become: true
            when: webservers_stack.mysql | default(false)
            tags:
                - mysql

        -   role: mariadb
            become: true
            when: webservers_stack.mariadb | default(true)
            tags:
                - mariadb

        -   role: apache2
            become: true
            vars:
                apache2_user: "{{ host_user }}"
                apache2_group: "{{ host_group }}"
            when: webservers_stack.apache2 | default(true)
            tags:
                - apache2

        -   role: nvm
            become: true
            vars:
                nvm_user: "{{ host_user }}"
                nvm_group: "{{ host_group }}"
            when: webservers_stack.nvm | default(true)
            tags:
                - nvm

        -   role: gantsign.golang
            when: webservers_stack.golang | default(false)
            tags:
                - golang

        -   role: geerlingguy.java
            become: true
            when: webservers_stack.java | default(false)
            tags:
                - java
