---
common_user: vagrant

common_packages:
  - "build-essential"
  - "dos2unix"
  - "gcc"
  - "git"
  - "git-lfs"
  - "imagemagick"
  - "libnotify-bin"
  - "libpng-dev"
  - "pv"
  - "re2c"
  - "unzip"
  - "vim"
  - "whois"
  - "zsh"
