# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

abort('Unable to find config.json.') unless File.exist?('./config.json')

config_data = JSON.parse(File.read('./config.json'))
ubuntu_version = config_data['ubuntu_version'] || '2004'
provider = ENV['VAGRANT_DEFAULT_PROVIDER'] || config_data['provider'] || 'virtualbox'
gpu_devices = config_data['gpu_devices'] || ['01:00.0', '01:00.1']

Vagrant.configure('2') do |config|
  config.vm.box = "generic/ubuntu#{ubuntu_version}"
  config.vm.hostname = config_data['hostname']

  if config_data.dig('disks', 'default', 'size')
    config.vm.disk :disk, size: config_data['disks']['default']['size'], primary: true
  end

  if config_data['forwarded_ports']
    config_data['forwarded_ports'].each do |port|
      config.vm.network 'forwarded_port',
        guest: port['guest'],
        host: port['host'],
        auto_correct: port.fetch('auto_correct', false)
    end
  end

#  config.vm.network 'private_network', ip: config_data['ip']

  ansible_host_path = File.expand_path('../ansible', __dir__)
  config.vm.synced_folder ansible_host_path, '/home/vagrant/ansible',
    type: 'nfs',
    mount_options: ['rw', 'tcp', 'nolock', 'actimeo=1'],
    linux__nfs_options: ['rw', 'no_subtree_check', 'all_squash', 'async']

  config_data['folders']&.each do |folder|
    host_path = File.expand_path(folder['from'], __dir__)
    guest_path = folder['to']
    config.vm.synced_folder host_path, guest_path,
      type: 'nfs',
      mount_options: ['rw', 'tcp', 'nolock', 'actimeo=1'],
      linux__nfs_options: ['rw', 'no_subtree_check', 'all_squash', 'async']
  end

  if provider == 'virtualbox'
    config.vm.provider 'virtualbox' do |vb|
      vb.memory = config_data['memory']
      vb.cpus = config_data['cpus']
      vb.name = "#{config_data['hostname']}-vbox"
      vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on'] if config_data['should_guest_know_the_host_network']

      config.vm.network 'private_network', ip: config_data['ip'], adapter: 2
    end
  elsif provider == 'libvirt'
    config.vm.provider 'libvirt' do |lv|
      lv.memory = config_data['memory']
      lv.cpus = config_data['cpus']
      lv.graphics_type = 'none'

      config.vm.network 'private_network', ip: config_data['ip'], adapter: 3
    end
  else
    abort("devbox does not support the provider: #{provider}")
  end

  # Re-enable the shared "/vagrant" directory.
  # The generic boxes disable this behavior (for a reason).
  # To make my live easier and this repo is just about local
  # environment, those reasons do not really apply.
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
  SHELL

  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = '/home/vagrant/ansible/site.yaml'
    ansible.galaxy_role_file = '/home/vagrant/ansible/requirements.yaml'
    ansible.inventory_path = '/home/vagrant/ansible/development.ini'
    ansible.limit = 'all'
  end
end
