---
- name: Check if kubectl binary exists
  ansible.builtin.stat:
    path: "{{ kubectl_bin_path }}"
  register: kubectl_binary_exists
  tags:
    - kubectl_setup

- name: Check if kubectl bash completions exists
  ansible.builtin.stat:
    path: "{{ kubectl_bash_completions_path }}"
  register: kubectl_bash_completion_file_exists
  tags:
    - kubectl_setup

- name: Download kubectl into temporary binary path
  ansible.builtin.get_url:
    url: "{{ kubectl_download_url_kubernetes }}"
    dest: "{{ kubectl_tmp_bin_path }}"
    mode: "0755"
  when: >
    not kubectl_binary_exists.stat.exists
  tags:
    - kubectl_setup

- name: Copy temporary kubectl to binary path
  ansible.builtin.copy:
    remote_src: true
    src: "{{ kubectl_tmp_bin_path }}"
    dest: "{{ kubectl_bin_path }}"
    mode: a+x
  when: >
    not kubectl_binary_exists.stat.exists
  tags:
    - kubectl_setup

- name: Check kubectl bash completion for changes
  ansible.builtin.shell:
    cmd: >
      set -euo pipefail
      && {{ kubectl_bin_path }} completion bash
      | cmp - {{ kubectl_bash_completions_path }}
    executable: /usr/bin/env bash
  failed_when: false
  changed_when: false
  register: kubectl_has_bash_completion_changes
  tags:
    - kubectl_setup

- name: Add kubectl bash completions
  ansible.builtin.shell: "{{ kubectl_bin_path }} completion bash > {{ kubectl_bash_completions_path }}"
  when: >
    not kubectl_bash_completion_file_exists.stat.exists
    or kubectl_has_bash_completion_changes.stderr | length > 0
  register: kubectl_bash_completions_has_been_added
  changed_when: kubectl_bash_completions_has_been_added.rc != 0
  tags:
    - kubectl_setup

- name: Always export env KUBECONFIG
  ansible.builtin.template:
    src: kubeconfig.sh.j2
    dest: /etc/profile.d/kubeconfig.sh
    mode: "0644"
  when: kubectl_kube_config_path | default(false)
  tags:
    - kubectl_setup

- name: Keep KUBECONFIG when suing
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    block: "{{ lookup('template', 'kubeconfig.sh.j2') }}"
    marker: "# {mark} Ansible(smoothie.kubectl): Keep KUBECONFIG when suing"
  when: kubectl_kube_config_path | default(false)
  tags:
    - kubectl_setup

- name: Download kubectx
  ansible.builtin.git:
    repo: "{{ kubectl_kubectx_repo }}"
    dest: "{{ kubectl_kubectx_download_path }}"
    version: "{{ kubectl_kubectx_version }}"
    single_branch: true
  when: kubectl_is_kubectx_enabled
  tags:
    - kubectl_setup

- name: Add kubectx binary
  ansible.builtin.file:
    src: "{{ kubectl_kubectx_download_path }}/kubectx"
    dest: "{{ kubectl_kubectx_bin_path }}"
    state: link
  when: kubectl_is_kubectx_enabled
  tags:
    - kubectl_setup

- name: Add kubectx bash completions
  ansible.builtin.file:
    src: "{{ kubectl_kubectx_download_path }}/completion/kubectx.bash"
    dest: "{{ kubectl_kubectx_bash_completions_path }}"
    state: link
  when: kubectl_is_kubectx_enabled
  tags:
    - kubectl_setup

- name: Add kubens binary
  ansible.builtin.file:
    src: "{{ kubectl_kubectx_download_path }}/kubens"
    dest: "{{ kubectl_kubens_bin_path }}"
    state: link
  when: kubectl_is_kubectx_enabled
  tags:
    - kubectl_setup

- name: Add kubens bash completions
  ansible.builtin.file:
    src: "{{ kubectl_kubectx_download_path }}/completion/kubens.bash"
    dest: "{{ kubectl_kubens_bash_completions_path }}"
    state: link
  when: kubectl_is_kubectx_enabled
  tags:
    - kubectl_setup
