---
# Highly inspired by geerlingguy.docker/tasks/docker-compose.yaml

-   name: Check current k9s version
    command: "{{ k9s_bin_path }} --version"
    register: k9s_vsn
    check_mode: false
    changed_when: false
    failed_when: false
    tags:
        - k9s_setup

-   set_fact:
        k9s_current_version: "{{ k9s_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
    when: >
        k9s_vsn.stdout is defined
        and (k9s_vsn.stdout | length > 0)
    tags:
        - k9s_setup

-   name: Delete existing k9s version if it's different
    file:
        path: "{{ k9s_bin_path }}"
        state: absent
    when: >
        k9s_current_version is defined
        and (k9s_version | regex_replace('v', '')) not in k9s_current_version
    tags:
        - k9s_setup

-   name: Make sure k9s tmp path directory exists
    file:
        path: "{{ k9s_tmp_dir }}"
        state: directory
    when: >
        (k9s_current_version is not defined)
        or (k9s_current_version | length == 0)
        or (k9s_current_version is version((k9s_version | regex_replace('v', '')), '<'))
    tags:
        - k9s_setup

-   name: Download k9s into tmp path
    unarchive:
        src: "{{ k9s_download_url }}"
        dest: "{{ k9s_tmp_dir }}"
        remote_src: true
        mode: 0755
    register: k9s_download
    when: >
        (k9s_current_version is not defined)
        or (k9s_current_version | length == 0)
        or (k9s_current_version is version((k9s_version | regex_replace('v', '')), '<'))
    tags:
        - k9s_setup

-   name: Copy k9s binary into place
    copy:
        src: "{{ k9s_tmp_path }}"
        dest: "{{ k9s_bin_path }}"
        mode: 0755
        remote_src: true
    when: k9s_download is changed
    tags:
        - k9s_setup

-   name: Check if k9s bash completions exists
    stat:
        path: "{{ k9s_bash_completions_path }}"
    register: k9s_bash_completion_file_exists
    tags:
        - k9s_setup

-   name: Check k9s bash completion for changes
    shell: "{{ k9s_bin_path }} completion bash | cmp - {{ k9s_bash_completions_path }}"
    failed_when: false
    changed_when: false
    register: k9s_has_bash_completion_changes
    tags:
        - k9s_setup

-   name: Add k9s bash completions
    shell: "{{ k9s_bin_path }} completion bash > {{ k9s_bash_completions_path }}"
    when: >
        not k9s_bash_completion_file_exists.stat.exists
        or k9s_has_bash_completion_changes.stderr | length > 0
    tags:
        - k9s_setup
